### ISSUE TITLE
Migrate CI away from Travis

### ISSUE THREAD

**Issue by reedy** [wikimedia/php-cssjanus-archived#37]
As it's not running at all :(

* [ ] CI
* [ ] IRC Notifications
* [ ] coveralls

**Comment by reedy** [comment]
Current patch doesn't do coveralls or notifications - https://github.com/wikimedia/php-cssjanus/blob/086787f/.travis.yml#L15-L24

**Comment by Krinkle** [comment]
Declining in favour of moving to Wikimedia Gerrit.
